# -*- coding: utf-8 -*-
"""dolares

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LmgohS9zDReU_BAY8vrK3qWD6k4uhlx6
"""

def convertir():

      d=int(input("1 pesos a dolares 2 dolares a pesos"))
      t= float(input("Digita la tasa de cambio"))
      if d==1:
         plata=int(input("digita los pesos"))
         print(plata/t)

      else:
         plata=int(input("digita los dolares"))
         print(plata*t)
convertir()

def menu():
    opcion = 1
    while opcion != 0:
        opcion = int(input("0. Salir 1. Convertir: "))
        if opcion == 1:
            convertir()

menu()     
